version: '3.8'
services:

  nginx:
    container_name: nginx
    build:
      context: './'
      dockerfile: './containers/nginx/Dockerfile'
    ports:
      - "80:80"
      - "443:443"
    networks:
      - server
    restart: always

  node:
    container_name: node
    build:
      context: './'
      dockerfile: './containers/node/Dockerfile'
    volumes:
      - ./src/:/usr/src/app/src
      - ./public/:/usr/src/app/public
      - ./scripts/:/usr/src/app/scripts
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - server
    restart: always

networks:
  server:
    driver: bridge
